language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - NETTE=nette-2.4-dev TESTER_RUNTIME="php"
    - NETTE=nette-2.4 TESTER_RUNTIME="php"
    - NETTE=nette-2.3 TESTER_RUNTIME="php"

matrix:
  include:
    - php: 5.6
      env: NETTE=nette-2.3 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable" TESTER_RUNTIME="php"
    - php: 7.0
      env: NETTE=nette-2.4 COVERAGE="--coverage ./coverage.xml --coverage-src ./src" TESTER_RUNTIME="phpdbg"
  exclude:
    - php: 5.4
      env: NETTE=nette-2.4-dev TESTER_RUNTIME="php"
    - php: 5.4
      env: NETTE=nette-2.4 TESTER_RUNTIME="php"
    - php: 5.5
      env: NETTE=nette-2.4-dev TESTER_RUNTIME="php"
    - php: 5.5
      env: NETTE=nette-2.4 TESTER_RUNTIME="php"
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update
  - wget -O /tmp/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php /tmp/composer-nette

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - travis_retry composer create-project --no-interaction kdyby/code-checker /tmp/code-checker
  - travis_retry wget -0 /tmp/coveralls.phar wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
  - vendor/bin/tester $COVERAGE -s -p $TESTER_RUNTIME -c ./tests/php.ini-unix ./tests/KdybyTests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php /tmp/code-checker/src/code-checker.php --short-arrays

after_script:
  - if [ "$COVERAGE" != "" ]; then php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
